# Generated by Django 3.2.8 on 2021-12-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificates'),
        ),
    ]
