# Generated by Django 3.2.8 on 2021-12-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_certificate_certificate_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
